export const QUERY_KEYS = {
  CRM_PROVIDERS: 'CRM_PROVIDERS',
  PROJECTS: 'PROJECTS',
  USER_INFO: 'USER_INFO',
  LEAD_CUSTOM_FIELDS: 'LEAD_CUSTOM_FIELDS',
  CRM_OBJECT_FIELDS: 'CRM_OBJECT_FIELDS',
  STAGE_FILTERS: 'STAGE_FILTERS',
  FILTERED_DATA: 'FILTERED_DATA',
  STAGE_CONVERSIONS: 'STAGE_CONVERSIONS',
  PROJECT_BREAKDOWNS: 'PROJECT_BREAKDOWNS',
  PROJECT_BREAKDOWN_DETAIL: 'PROJECT_BREAKDOWN_DETAIL',
  PROJECT_FORECAST_DETAIL: 'PROJECT_FORECAST_DETAIL',
  CURRENCY: 'CURRENCY',
};
